CREATE DATABASE bakerydb; 

USE BAKERYDB;


SELECT * FROM goods;


SELECT food,price FROM goods;


SELECT FOOD FROM GOODS;


SELECT * FROM goods WHERE price = 3.25;


SELECT * FROM goods WHERE price = 3.25 OR price = 8.95;

SELECT * FROM GOODS WHERE PRICE > 3;

SELECT * FROM goods WHERE FOOD LIKE "%H%";

SELECT * FROM goods WHERE FOOD LIKE "%RT%";

SELECT * FROM goods WHERE FOOD LIKE "____";

SELECT * FROM goods WHERE PRICE > 3 OR FOOD LIKE "%KE";

SELECT * FROM goods WHERE PRICE IN (3.25,8.95,3.75);

SELECT * FROM goods WHERE  FOOD NOT LIKE "____";

SELECT * FROM goods WHERE PRICE IS NULL;

SELECT * FROM goods WHERE PRICE BETWEEN 3.25 AND 8.95;

SELECT * FROM GOODS  ORDER BY PRICE;