USE CARDB;

SELECT COUNT(*) FROM  CARMAKERS;

SELECT AVG(2) FROM CARMAKERS WHERE COUNTRY = 2;

SELECT MAX(COUNTRY) FROM CARMAKERS;

SELECT MIN(COUNTRY) FROM CARMAKERS;

SELECT COUNT(MAKER),COUNTRY FROM CARMAKERS GROUP BY COUNTRY;

SELECT  MAX(COUNTRY),FULLNAME FROM CARMAKERS GROUP BY COUNTRY;

SELECT MIN(COUNTRY),FULLNAME FROM CARMAKERS GROUP BY COUNTRY;

SELECT COUNT(MAKER),COUNTRY FROM CARMAKERS GROUP BY MAKER ORDER BY COUNT(MAKER);

SELECT DISTINCT(MAKER) FROM CARMAKERS;

SELECT COUNT(MAKER),COUNTRY FROM CARMAKERS  WHERE COUNTRY >= 3 GROUP BY MAKER