CREATE DATABASE reservationdb;

use reservationdb;

SELECT * FROM  RESERVATIONS;

SELECT FIRSTNAME,LASTNAME FROM  RESERVATIONS;

SELECT FIRSTNAME FROM  RESERVATIONS;

SELECT * FROM RESERVATIONS WHERE ADULTS = 2;

SELECT * FROM RESERVATIONS WHERE CHILDS = 1;

SELECT * FROM RESERVATIONS WHERE ADULTS <> 0;

SELECT * FROM RESERVATIONS WHERE RATE > 150;

SELECT * FROM RESERVATIONS WHERE FIRSTNAME LIKE "%A%";

SELECT * FROM RESERVATIONS WHERE LASTNAME LIKE "M%";

SELECT * FROM RESERVATIONS WHERE FIRSTNAME LIKE "_____";

SELECT * FROM RESERVATIONS WHERE FIRSTNAME LIKE "_____" AND ADULTS > 2;  

SELECT * FROM  RESERVATIONS WHERE ADULTS = 2 AND RATE = 250;

SELECT * FROM RESERVATIONS WHERE CHECKIN IN ( "01-Jan-10", "01-feb-10", "01-mar-10", "01-apr-10", "01-may-10");

SELECT * FROM RESERVATIONS WHERE CHECKIN NOT LIKE "%JAN%";

SELECT * FROM RESERVATIONS WHERE CHECKOUT IS NULL;

SELECT * FROM RESERVATIONS WHERE RATE BETWEEN 200 AND 250;

SELECT * FROM RESERVATIONS ORDER BY RATE ;