USE studentdb;

SELECT * FROM STUDENTS;

SELECT COUNT(*) FROM STUDENTS;

SELECT AVG(Grade) AS GRADES FROM STUDENTS;

SELECT MAX(Grade) AS GRADES FROM STUDENTS;

SELECT MIN(Grade) AS GRADES FROM STUDENTS;

SELECT COUNT(*) AS GRADES,CLASSROOM FROM STUDENTS GROUP BY CLASSROOM; 

SELECT AVG(Grade) AS GRADES,CLASSROOM FROM STUDENTS WHERE CLASSROOM = 101 OR CLASSROOM = 102 GROUP BY CLASSROOM;

SELECT MIN(Grade) AS GRADES,CLASSROOM FROM STUDENTS GROUP BY CLASSROOM;

SELECT MAX(Grade) AS GRADES,CLASSROOM FROM STUDENTS GROUP BY CLASSROOM;

SELECT COUNT(*) AS GRADES,CLASSROOM FROM STUDENTS GROUP BY CLASSROOM ORDER BY GRADES DESC; 

SELECT AVG(Grade) AS GRADES,CLASSROOM FROM STUDENTS GROUP BY CLASSROOM ORDER BY GRADES ;

SELECT MAX(Grade) AS GRADES,CLASSROOM FROM STUDENTS GROUP BY CLASSROOM ORDER BY GRADES ;

SELECT MIN(Grade) AS GRADES,CLASSROOM FROM STUDENTS GROUP BY CLASSROOM ORDER BY GRADES DESC;

SELECT MAX(grade) AS GRADES, Firstname, Lastname,classroom FROM STUDENTS GROUP BY FIRSTNAME ORDER BY GRADES DESC LIMIT 3;  

USE BAKERYDB ;